### ISSUE TITLE
Remove unsupported visualizers

### ISSUE THREAD

**Issue by jirihelmich** [tobice/payola-viz#4]
There is no need in listing them, it's confusing and it has no added value for the user.

**Comment by tobice** [comment]
Okay.

 Nevertheless, the Dashboard currently displays the total count of pipelines (taken from `pipeline_discovery` table) which includes the unsupported pipelines as well.  To make the behavior consistent, I decided to inform the user on the discovery screen that there have been some pipelines discovered that are not displayed because they are not supported. It's also a useful debug info in case the admin just forgets to activate a new visualizer.
